config/routes.rb
Rails.application.routes.draw do
  resources :subscriptions
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cutoff.rb
class Cutoff < ApplicationRecord
  validates_presence_of :name, :off_at

  has_many :subscriptions
  has_many :orders
  has_many :groups

  def week
    off_datetime = DateTime.now.all_week.to_a[off_at.wday - 1] + (off_at.localtime.seconds_since_midnight).seconds
    1.week.ago(off_datetime)..off_datetime
  end

  def off_time?
    DateTime.now >= week.end
  end

  def week_orders_created?
    groups&.last&.completed_at == week.end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :cutoff
  has_many :orders

  #cutoff created orders + new subscriptions created orders
  def group_orders
    orders.or(cutoff.orders.where(created_at: 1.week.ago(completed_at)..completed_at))
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  validates_uniqueness_of :order_id, scope: :meal_id
  validates_presence_of :name, :price, :quantity

  belongs_to :order
  belongs_to :meal
end

app/models/meal.rb
class Meal < ApplicationRecord
  enum state: { unactive: 0, active: 1 }

  has_and_belongs_to_many :subscriptions, join_table: 'subscriptions_meals', dependent: :destroy

  validates_uniqueness_of :name, :sku
  validates_presence_of :name, :description, :sku, :price

  # sort by SubscriptionsMeal's meal count
  def self.popular_meals
    meals_count = SubscriptionsMeal.where(subscription_id: Subscription.active.ids).group(:meal_id).count
    sorted_by_count_meal_ids = meals_count.sort { |a, b| b[1] <=> a[1] }.map { |mc| mc[0] }
    Meal.where(id: sorted_by_count_meal_ids.first(10))
  end
end

app/models/order.rb
class Order < ApplicationRecord
  serialize :deliver_info, Hash

  enum state: { pending: 0, delivery: 1, complete: 2 }

  belongs_to :user
  belongs_to :subscription
  belongs_to :cutoff
  belongs_to :group, optional: true
  has_many :line_items

  validates_uniqueness_of :number
  validates_presence_of :number

  before_validation :set_number, on: :create

  def self.create_by_subscription!(subscription, group_id = nil)
    Order.transaction do
      the_order = subscription.orders.create!(user_id: subscription.user_id, cutoff_id: subscription.cutoff.id, 
                                              cutoff_name: subscription.cutoff.name, deliver_info: subscription.deliver_info,
                                              total_quantity: subscription.meals.size, total: subscription.meals.sum(:price))
      the_order.update!(group_id: group_id) if group_id.present?
      subscription.meals.each do |meal|
        the_order.line_items.create!(meal_id: meal.id, name: meal.name, price: meal.price, quantity: subscription.subscriptions_meals.find_by(meal_id: meal.id).quantity)
      end
    end
  end

  private

  def set_number
    self.number = generate_number
  end

  def generate_number
    the_number = ''
    loop do
      the_number = "MS_#{DateTime.now.to_i}#{rand(1000...9999)}"
      break if Order.find_by(number: the_number).nil?
    end
    the_number
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  serialize :deliver_info, Hash

  enum state: { unactive: 0, active: 1, pause: 2 }

  belongs_to :user
  belongs_to :cutoff
  has_many :orders
  has_many :subscriptions_meals
  has_and_belongs_to_many :meals, join_table: 'subscriptions_meals', dependent: :destroy

  validates_presence_of :user_id, :cutoff_id, :deliver_info

  scope :old, ->(cutoff) { cutoff.subscriptions.where('created_at < ?', cutoff.week.begin ) }
end

app/models/subscriptions_meal.rb
class SubscriptionsMeal < ApplicationRecord
  belongs_to :subscription
  belongs_to :meal

  validates_uniqueness_of :subscription_id, scope: :meal_id
  validates_presence_of :subscription_id, :meal_id, :quantity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.user = current_user

    respond_to do |format|
      if @subscription.save
        Order.create_by_subscription!(@subscription)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:cutoff_id, :state, meal_ids: [], deliver_info: [:full_name, :address, :postcode, :phone])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealsSubscription</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cutoff %>
    <%= form.select :cutoff_id, Cutoff.all.map { |cutoff| [ cutoff.name, cutoff.id ] } %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.select :state, Subscription.states.map { |key, value| [ key, key ] } %>
  </div>

<div class="field">
    <%= form.label :deliver_info %>
    <ul>
    <%= form.fields_for :deliver_info do |addresses_form| %>
      <li>
        <%= addresses_form.label :full_name %>
        <%= addresses_form.text_field :full_name %>
      </li>
      <li>
        <%= addresses_form.label :address %>
        <%= addresses_form.text_field :address %>
      </li>
      <li>
        <%= addresses_form.label :postcode %>
        <%= addresses_form.text_field :postcode %>
      </li>
      <li>
        <%= addresses_form.label :phone %>
        <%= addresses_form.text_field :phone %>
      </li>
    <% end %>
  </ul>
</div>

<div class="field">
  <%= form.label :meals %>
  <%= form.collection_check_boxes :meal_ids, Meal.all, :id, :name %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Cutoff</th>
      <th>State</th>
      <th>Deliver info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.user_id %></td>
        <td><%= subscription.cutoff_id %></td>
        <td><%= subscription.state %></td>
        <td><%= subscription.deliver_info %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @subscription.user_id %>
</p>

<p>
  <strong>Cutoff:</strong>
  <%= @subscription.cutoff_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @subscription.state %>
</p>

<p>
  <strong>Deliver info:</strong>
  <%= @subscription.deliver_info %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>